modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 2 (GPLv2)"

[[mods]]
modId="sugarsnap"
version="2.1"
displayName="SugarSnap"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/Sam5065/SugarSnap"
authors="SamH"
description='''
A forge mod which adds features onto my own modpack
'''

[[dependencies.sugarsnap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




